build:
	javac Main.java

run:
	java Main

clean:
	cd graphics_algorithms && rm *.class && cd ..
	rm *.class 

get:
	mvn dependency:get -Ddest='C:\Users\Дима\Documents\1 ПРОЕКТЫ\Проекты Математика\explore\Линейная алгебра и аналитическая геометрия\dda_line\java\JUnit' -Dartifact=junit:junit:4.13


copy-dependency:
	mvn dependency:copy-dependencies -DoutputDirectory=OUTPUT_DIR